paper_crawling_task:
  description: >
    Periodically crawls academic websites for new research papers based on specified topics.
  expected_output: >
    A structured list of newly found research papers including titles, sources, and URLs.
  agent: paper_crawler_agent

text_extraction_task:
  description: >
    Extracts and cleans the text content from the provided research paper documents.
  expected_output: >
    A list of extracted texts corresponding to each paper's ID.
  agent: text_extraction_agent

summarization_task:
  description: >
    Generates summaries of the cleaned text for the extracted research papers.
  expected_output: >
    A list of summaries corresponding to each paper's ID.
  agent: summarization_agent

topic_classification_task:
  description: >
    Classifies the papers into relevant subject areas based on the extracted text.
  expected_output: >
    A list of topics assigned to each paper's ID.
  agent: topic_classifier_agent

report_generation_task:
  description: >
    Compiles the generated summaries and classified topics into a structured report.
  expected_output: >
    A formatted report summarizing recent research highlights.
  agent: report_generator_agent
