from pydantic import BaseModel, Field


class AgentExecutionStep(BaseModel):
    agent_name: str = Field(
        description="The name of the specialized agent responsible for a specific step in the task."
    )
    action_description: str = Field(
        description="A detailed description of what the agent will do in this step."
    )
    agent_prompt: str = Field(
        description="The prompt to be sent to the agent for execution."
    )


class OrchestrationPlan(BaseModel):
    final_answer: str = Field(
        description="The conclusive output generated by coordinating multiple agents to solve the given task."
    )
    agent_execution_plan: list[AgentExecutionStep] = Field(
        description="A sequential list detailing the agents to be invoked and their responsibilities in the task pipeline."
    )
